version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "user-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l6mg5bbqxuku"
s3_prefix = "user-api"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
